name: Publish to Maven Central Staging

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Gradle
        run: gradle build

      - name: Decrypt secring
        run: ./.github/scripts/decrypt_secring.sh
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}

      - name: Fill gradle properties
        run: |
          ./.github/scripts/set_gradle_properties.sh ossrhUsername ${{ secrets.SONATYPE_USERNAME }}
          ./.github/scripts/set_gradle_properties.sh ossrhPassword '${{ secrets.SONATYPE_PASSWORD }}'
          ./.github/scripts/set_gradle_properties.sh signing.keyId ${{ secrets.SIGNING_KEYID }}
          ./.github/scripts/set_gradle_properties.sh signing.password ${{ secrets.SIGNING_PASSWORD }}
          ./.github/scripts/set_gradle_properties.sh signing.secretKeyRingFile $HOME/secrets/secring.pgp

      - name: Publish to Maven Central Staging repository
        run: |
          ./gradlew :microconfig-core:publishNexusPublicationToMavenRepository
          ./gradlew :microconfig-api:publishNexusPublicationToMavenRepository
          ./gradlew :microconfig-cli:publishNexusPublicationToMavenRepository
          ./gradlew :utils:publishNexusPublicationToMavenRepository
          ./gradlew :microconfig-cli:publishShadowPublicationToMavenRepository
